[2019-03-28 11:45:44,444] - Log.py] - ERROR: ConnectionError
[2019-03-28 11:46:09,001] - Log.py] - ERROR: ConnectionError
[2019-03-28 11:47:08,536] - Log.py] - ERROR: ConnectionError
[2019-03-28 11:47:29,899] - Log.py] - ERROR: ConnectionError
